### ISSUE TITLE
Enquiry Before Purchase

### ISSUE THREAD

**Issue by pureskar** [voinsource/SmartWebView-Pro#1]
Will i be able to send my app's push notification for multiple dynamic users?
Also, since Firebase Notification is provided, does that mean Firebase Login & Signup option would be provided in the app as well?

**Comment by mgks** [comment]
Yeah sure,
you can send notifications to individual or multiple users/groups from firebase panel or directly from your server. It's easy.

There's no login method in SWV for now.
